### ISSUE TITLE
Fill in some missing repo details

### ISSUE THREAD

**Issue by mattmassicotte** [jessegrosjean/SummarizedCollection#1]
Jesse! I'm finally giving this library a more serious look.

I noticed a few things that are missing that only you can fix. There are also a few things that technically others could fix, but should probably be decisions you make. These ideas are mainly coming from a [package template repo](https://github.com/mattmassicotte/PackageTemplate) I set up, and it includes suggestions if you need some.

- license
- Code of conduct
- About is empty
- Repo tags

**Comment by jessegrosjean** [comment]
Good ideas ... I've added license and about. I think for now I won't add repo tags or code of conduct. I don't know that I want many people to find project in current state. I can't get myself to read to the end of any code of conduct that I find, much less understand details. I think I'm getting old.
